### ISSUE TITLE
Verify two-point wave sine component removal w.r.t. `nsubsteps`

### ISSUE THREAD

**Issue by michaelcdevin** [sandialabs/WecOptTool#194]
The removal of the sine component of the two-point wave in #191 changes the evaluation of some of the constraints in the optimization problem in `nsubsteps > 1`. We should test the impact of this, and look into the option of removing `nsubsteps` and instead use a larger number of frequencies with FFT (which has unconfirmed cofunctionality with `autograd`). See https://github.com/SNL-WaterPower/WecOptTool/issues/181#issuecomment-1426175450.

Actions:
- [ ]  Run the tutorial with 4x more frequencies in the same range (0.25x `f0`) and verify we get similar results.
- [ ]  Verify that `autograd` can handle the FFT
- [ ]  Consider moving to FFT instead of time-matrix and not allowing `nsubsteps`

**Comment by cmichelenstrofer** [comment]
Closing this.
