### ISSUE TITLE
Feature request: Allow additional states when using the PTO module

### ISSUE THREAD

**Issue by cmichelenstrofer** [sandialabs/WecOptTool#198]
**Feature description.**
Allow using the PTO module even when you have additional intermediate states. 

**Issue addressed.**
Although it is meant as "examples", the PTO module is very useful in most cases. One limitation we are running into is that it requires a specific size for the `x_opt` and does not allow for additional states in `x_opt`.

**Describe the solution you'd like**
Uncertain. Some way to allow the PTO to only use a portion of the `x_opt` and allow for arbitrary size of `x_opt` might do it. 

**Describe alternatives you've considered**
We can just leave it as is. It is meant as example and it is easy to copy-paste the parts you need. Alternatively instead/in addition to a big PTO class we can simply provide simple code snippets that can be copy-pasted and altered to each use case. 

**Interest in leading this feature development?**
Not at this time.

**Additional information**

**Comment by jtgrasb** [comment]
This issue has been addressed with #226. I don't have the right permissions to close it though.
