### ISSUE TITLE
ATTENTION: WecOptTool is migrating to github.com/sandialabs/WecOptTool

### ISSUE THREAD

**Issue by michaelcdevin** [sandialabs/WecOptTool#235]
FYI @cmichelenstrofer @akeow @dtgaebe @jtgrasb @kevmoor @mbruggs @michaelcdevin @ryancoe @ssolson @w-bonelli @smallduan @Jinhyuk-Yu

The GitHub repository for WecOptTool will now be hosted at [https://github.com/sandialabs/WecOptTool](https://github.com/sandialabs/WecOptTool), with the documentation site at [https://sandialabs.github.io/WecOptTool](https://sandialabs.github.io/WecOptTool). **Please direct all new issues, pull requests, and discussions to this new URL**. All pre-existing commits, issues, and pull requests have been automatically transferred to this new location.

[https://github.com/SNL-WaterPower/WecOptTool](https://github.com/SNL-WaterPower/WecOptTool) will continue to exist solely to redirect the documentation site correctly and will not host any code or issues.

All of the git related forks and links to this repository (`git clone`, `git fetch`, `git push`, etc.) will automatically redirect to this new repository location, so **there is no action needed from users who have simply forked this repo**. If you have set a `git remote` to github.com/SNL-WaterPower/WecOptTool directly (i.e. *not* to your personal fork), you can update this from the command line with:
```
git remote set-url upstream https://github.com/sandialabs/WecOptTool
```
Internal links to this new repo location on the README, examples, and docstrings will be broken for a few hours, but will be updated shortly.

**Comment by ryancoe** [comment]
FYI @rebeccamccabe @johannes-spinneken @bretbosma @ThBoerner @gbacelli @dforbush2
