### ISSUE TITLE
BUG: `test_atol` randomly fails occasionally

### ISSUE THREAD

**Issue by michaelcdevin** [sandialabs/WecOptTool#245]
**Describe the bug**
The `test_atol` test within TestSubsetClose in `test_core.py` will pass without issue the majority of the time, but once in a while will fail with the following error:
```
TypeError: only size-1 arrays can be converted to Python scalars
```
This causes the CI to fail sometimes (example [here](https://github.com/sandialabs/WecOptTool/actions/runs/4610782818/jobs/8149669325)), but rerunning the fail job almost always returns a success.

**To Reproduce**
Run `pytest tests/test_core.py -k test_atol`. It will usually pass, but will encounter a `TypeError` on rare occasion.

**Expected behavior**
The testing suite consistently passes or fails for an unchanged codebase. 

**Observed behavior**
The testing suite results are not consistent.

**Comment by cmichelenstrofer** [comment]
This really should not happen in practice...
