### ISSUE TITLE
Waves and frequencies in tutorials 

### ISSUE THREAD

**Issue by cmichelenstrofer** [sandialabs/WecOptTool#252]
We need to :
- [x] edit all the tutorials to specify the waves first and choose an appropriate frequency array for the wave considered. 
- [x] In tutorial 1 explain how to do this.

@ryancoe what are some key things we want too point out? 
- For completely linear models and regular waves it is sufficient to capture the wave frequency
- For non-linearities we want at least a few harmonics.

**Comment by ryancoe** [comment]
Yes, I think that's right!

**Comment by ryancoe** [comment]
Ideally, we will complete #223 prior to this issue, as that will allow further refinement of the frequency array and we'll need to explain this in the tutorials.
