### ISSUE TITLE
Not all references showing up in built documentation.

### ISSUE THREAD

**Issue by cmichelenstrofer** [sandialabs/WecOptTool#256]
The **References** page is not showing all the references in the `.bib` file.

**Comment by michaelcdevin** [comment]
The references that are not appearing on the *References* page are not cited elsewhere in the documentation, so `sphinxcontrib-bibtex` does not know to look for them. We can include the reference keys explicitly in `references.rst` to include them, see [here](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#listing-citation-keys)
