### ISSUE TITLE
Minor rendering problems in documentation

### ISSUE THREAD

**Issue by ryancoe** [sandialabs/WecOptTool#320]
There's a couple minor rendering bugs in the documentation, e.g., 

![image](https://github.com/sandialabs/WecOptTool/assets/5589887/868f3e0a-fb62-4576-9e3e-a7a0b5fe809d)

**Comment by michaelcdevin** [comment]
Some other rendering problems I've found:

**Tutorial 1**:
* Lists not rendering in Section 1 
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/b5158053-ead5-4a1e-a138-87e57d320ea6)
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/60721083-e3e7-4382-a7e9-4df1b1d52d62)

**Tutorial 4**:
* Lists not rendering in Sections 1.4 and 1.5
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/16067ba0-6bab-46a2-b1bc-bba1bf98fad2)
* Math not rendering right in Section 1.6 
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/f853a2d3-e1cc-49c6-9dc4-f5b7b383d002)

**Comment by michaelcdevin** [comment]
Resolved in #339
